services:
#  resizer:
#    container_name: resizer
#    build: .
#    volumes:
#      - ./:/app
#    working_dir: /app

  resizer-test-nginx:
    image: nginx:alpine
    container_name: nginx-resizer
    ports:
      - "8081:80"
    volumes:
      - ./test/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./test/images:/usr/share/nginx/html/images:ro
      - ./test/404.html:/usr/share/nginx/html/404.html:ro