logger:
  level: "info"
storage:
  cache_size: 5
  cache_dir: "./tmp"
  default_image_quality: 90
  max_uploaded_image_size: 10 # in megabytes
  read_timeout: 10
server:
  host: "localhost"
  port: 8080
