name: Image resizer tests

on:
  push:
    branches: [dev,main]

env:
  GO111MODULE: "on"

jobs:
  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.24

      - name: Check out code
        uses: actions/checkout@v4

      - name: make lint
        run: make lint

      - name: make build
        run: make build

      - name: make test
        run: make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose- $(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run integration tests
        run: make integration-test
